defaults: &defaults
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: acceptto
  password: vesper

development:
  <<: *defaults
  database: sso_client
  
production:
  <<: *defaults
  database: sso_client_production

test:
  <<: *defaults
  database: sso_client_test